[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "git-tools-app"
version = "0.1.0"
description = "GTA (Git Tool App)"
authors = [
    { name = "b1nswing" }
]
requires-python = ">=3.8"
dependencies = [
    "requests",
    "pygame",
    "questionary",
    "python-dotenv"
]

[project.scripts]
gta = "git_tools_app.main:main"

[tool.setuptools]
include-package-data = true